name: Test

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - uses: ryohidaka/action-setup-sqlite@v1.2.0
        with:
          version: "3.43.2"

      - uses: nrwl/nx-set-shas@v4

      - name: nx affected:test
        run: npx nx affected -t test --base origin/master